### ISSUE TITLE
您好，有点疑问?

### ISSUE THREAD

**Issue by whereis-mark** [hongshixian/CSI_reader#2]
len是字长吗，不是以字节为单位?
real_bin和imag_bin的那几个移位和与或操作具体要做什么呢?

**Comment by hongshixian** [comment]
第一个问题：这里可能是我的失误，len的单位是字节，表示有效负载部分的长度；
第二个问题：有效负载却并非按字节储存：复数以8bit实部、8bit虚部的方式储存，但是在这些数据里穿插有3bit的subc头部。这将导致有效负载第一个字节中前3bit是subc头部、后5bit是实部的前5个bit，实部的后3个bit在第二个字节中。
所以为了得到完整的8bit实部（real_bin）和8bit虚部（imag_bin），需要移位操作得到3bit和5bit，并组合在一起。
详见:subc的结构。
